export KMS_URI='127.0.0.1:8443'
export ROOT_CA='ssl/root.crt'
export SENDER_SAE_CRT='ssl/sae_001.crt'
export SENDER_SAE_KEY='ssl/sae_001.key'
export RECEIVER_SAE_CRT='ssl/sae_001.crt'
export RECEIVER_SAE_KEY='ssl/sae_001.key'
export SENDER_STRICT_ROLE='rx'
export RECEIVER_STRICT_ROLE='rx'
